---
title: "Visualization Project"
author: "Abhishek Chakraborty"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Desktop/Visualization")
```


```{r}
data = read.csv("diabetes.csv")
attach(data)
```


### Useful Libraries

```{r}
library(ggplot2)
library(reshape2)
library(tidyverse)
library(egg)
```


```{r}
str(data)
summary(data)

```

### Distribution of Variables

```{r}
md = melt(data)
ggplot(md,aes(x = value,fill = variable))+
  geom_histogram(binwidth = 1)+
  facet_wrap(~variable,scales = "free")

```

### Impact of Age over Outcome

```{r}

ggplot(data,aes(x = Age,fill = factor(Outcome)))+
  geom_density(alpha = 0.7)+
  labs(title = "Impact of Age over Outcome")


```

### Relationship between Glucose and Blood Pressure

```{r}
ggplot(data,aes(x = Glucose, y = BloodPressure, size = Age, color = as.factor(Outcome)))+
  geom_jitter(alpha = 0.5)+
  labs(title = "Glucose Level and Blood Pressure against Age")
```

### Distribution of BMI
```{r}
ggplot(data,aes(x = BMI,fill = factor(Outcome)))+
  geom_density(alpha = 0.4)+
  labs(title = "Distribution of BMI")
```

### Relationship between Glucose and Diabetes Pedigree Function vs Pregnancies
```{r}
ggplot(data,aes(x = Glucose,y = DiabetesPedigreeFunction,color = Pregnancies))+
  geom_jitter(alpha = 0.6 )+
  labs(title = "Relationship between Glucose and Diabetes Pedigree Function vs Pregnancies")


```

### Correlation Matrix
```{r}
library(ggcorrplot)
c = round(cor(data),1)

ggcorrplot(c,lab = TRUE)+
  labs(title = "Correlation Matrix of the attributes")



```

### Relationship between Insulin and Glucose
```{r}
ggplot(data,aes(x = Insulin,y = Glucose))+
  geom_point(aes(color = Outcome))+
  geom_smooth()


```

### Boxplot of the variables
```{r}
b1 =  ggplot(data,aes(y = Pregnancies))+
  geom_boxplot(outlier.color = "violet")

b2 =  ggplot(data,aes(y = Glucose))+
  geom_boxplot(outlier.color = "grey")

b3 =  ggplot(data,aes(y = BloodPressure))+
  geom_boxplot(outlier.color = "blue")

b4 =  ggplot(data,aes(y = SkinThickness))+
  geom_boxplot(outlier.color = "green")

b5 =  ggplot(data,aes(y = Insulin))+
  geom_boxplot(outlier.color = "yellow")

b6 =  ggplot(data,aes(y = BMI))+
  geom_boxplot(outlier.color = "orange")

b7 =  ggplot(data,aes(y = DiabetesPedigreeFunction))+
  geom_boxplot(outlier.color = "red")

b8 =  ggplot(data,aes(y = Age))+
  geom_boxplot(outlier.color = "black")

ggarrange(b1,b2,b3,b4,b5,b6,b7,b8,ncol = 4,nrow = 2)
```


